### PR TITLE
Add Robigalia

### PR DESCRIPTION
**Pull request by kephas**

### CODE REVIEW

**Comment by dckc** [comment]
as noted in CONTRIBUTING.md, "Emphasis is on active projects, preferably with dated items that show recent progress." Is there some recent release or article you can cite?

**Comment by dckc** [comment]
https://gitlab.com/robigalia/runner/pipelines suggests it's been 9 months since the last commit (7c4b0d64). Is that right?

**Comment by kephas** [comment]
It seems pretty inactive, sorry I didn't see there were such guidelines.

**Comment by dckc** [comment]
I stopped by their IRC channel and there is more recent work. I think they pointed me to some talks; one of those would serve as a dated item.

**Comment by dckc** [comment]
I just took another look... not much going on.

**Pull request closed without merging**
